### ISSUE TITLE
Introduce smart OFF AIR schedules

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#103]
E.g., mixes during night, short tracks between shows during the day

**Comment by baxgas** [comment]
Let's say we have mixes from 23:00-12:00 h (from the last show-time until noon), and the short tracks between 12:00-23:00 h?
I made a new playlist Between Shows and added some tracks, but I think we need some more also, it will be quite boring if 10 tracks repeat all the time...
For now I left them also in the OFF AIR playlist

**Comment by gammaw** [comment]
@gammaw pull this (https://github.com/mmmnmnm/lahmacun/commit/46f5bc61876f9dbcdc0d274cc5f5555bdccb0ce4) on prod at some point

**Comment by gammaw** [comment]
No coding issue
