### ISSUE TITLE
Show URL in player

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#115]

**Comment by gammaw** [comment]
@baxgas Good stuff so far! 
Live DJ names are transferred differently in JSON: 

`"live":{"is_live":true,"streamer_name":"MMN radio"}`

We should use `streamer_name` there.

**Comment by gammaw** [comment]
@baxgas `default_url` is hard-coded. It's not very good for two reasons: 1) we cannot test it on dev, 2) we reveal our domain :) 
Is it a way to make it parametric?

**Comment by baxgas** [comment]
It is just a default fallback, should be only in cases where everything else fails. We have server checks on php side, not in js
