### ISSUE TITLE
Make album photo clickable

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#142]
Currently, only text is clickable.

**Comment by baxgas** [comment]
It is indeed a bug in Gutenberg, but found this workaround

> Although tedious, but simple (even for a non-developer), if you insert a gallery block and add gallery images and then set number of columns for block and set link to: "Attachments", you can then go to the block and "edit in html" and just replace the href=urls on each image with the link you want plus _target="blank" if you want to open in new tab, etc. For a small gallery, it is not too bad but they do need to fix this.

https://github.com/WordPress/gutenberg/issues/8929#issuecomment-522345028

**Comment by baxgas** [comment]
Unfortunately the WP editor is broken now (HTML code), adding new galleries can be done separately in a block, then appending the corrected html

**Comment by gammaw** [comment]
Nice digging! Thanks for the workaround!

**Comment by baxgas** [comment]
Adding new gallery messed up the code again, I will automate it through javascript, that it happens automatically.

**Comment by gammaw** [comment]
Thanks, works like a charm! Tested, merged into master, branch closed, issue closed.

**Comment by butifarra** [comment]
> Unfortunately the WP editor is broken now (HTML code), adding new galleries can be done separately in a block, then appending the corrected html

Hi! I have been searching a solution for days, but to no avail. It happened to me, I made it work, but the gallery in question, and any new galleries, are broken. I don´t grasp what you mean by "append the correct HTML", I am new to this. Can you explain more please? Thanks in advance.
