### ISSUE TITLE
Add new show: Svadhyaya Önkutatólabor

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#157]
- [x] link sub page on home (shows lister html) -> Git
- [x] add sub page to menu

**Deadline**: Dec 3

**Comment by baxgas** [comment]
TODO (?)
Make the Shows lister html load dynamically on the Home page, so we don't need to edit twice?
(I made it so the 3rd party admin person (sweet dreams...) can add the stuff there, but it seems we'll make the changes anyway)

**Comment by gammaw** [comment]
Good idea although news shows should not be added to frequently but still, if there is a quick fix it would be nice. I added a new issue: https://github.com/mmmnmnm/lahmacun/issues/158
