### ISSUE TITLE
Hrefs don't work on AJAX subpage

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#16]
Example: http://127.0.0.1/shows/lazy-calm-raga/ (link may be depricated)

**Comment by mmmnmnm** [comment]
fixed by 70397e6fcbcd69baf82921da23d82d1e08c8c30b (@baxgas)

**Comment by gammaw** [comment]
@baxgas would it be possible that a href opens in a new table only if it's an external link. It's strange with our schedule table when one clicks on a show and it open a new tab.

**Comment by gammaw** [comment]
fixed by no idea which commit
