### ISSUE TITLE
Show categories 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#160]
Concept?

**Comment by gammaw** [comment]
Báró: English, Music, Chat (beszélgetős)

**Comment by baxgas** [comment]
A correction, they should not be Categories, but Tags – we already use Categories for News and Shows

**Comment by gammaw** [comment]
G's additional suggestion: have separate page for this

**Comment by baxgas** [comment]
@gammaw is it for tagging the Shows?

**Comment by gammaw** [comment]
@baxgas the idea in the last board meeting was to have a separate page for showing all shows where we have more space for categories/tags etc. Right now shows are only listed in the drop-down menu (and in the timetable). The idea is to have a separate page for all shows.

**Comment by baxgas** [comment]
@gammaw There is! [URL]/shows/ – using the same template as the News

**Comment by gammaw** [comment]
True. That's a good start probably. I guess what G meant is that you cannot navigate to this page from the menu (e.g., by clicking on Shows in the main menu). Which is good, because it's not a particularly nice page right now.

**Comment by baxgas** [comment]
isn't this the same as #224  ?

**Comment by gammaw** [comment]
Yes, you're right, they are related. I see two tasks here: 1) show categories somehow (this could be in the menu view too) and 2) have a separate page for shows & categories, a page which is more spacious, can be shared etc. W

While I was running today I was thinking that we could add some fancy text-based search engine to the whole thing but maybe it's too visionary for now. I'm interested to try one of those technologies (e.g., full-text search). Such a search engine would be useful to search in archives too (#191).

**Comment by gammaw** [comment]
Message from comm workshop: give this one priority! 

Hints: 
- category for less more rigid, static groups -> from arcsi? 
- tags for more fleixble, random, manually added groups (even single-member groups).

**Comment by baxgas** [comment]
We already implemented the tags, just need to add them to the content (eg. our-site/tag/music) and shown on the Show page
Can be developed more of course, but first let's start with the content to have some real-life examples

**Comment by pvj** [comment]
@baxgas perhaps you could open a thread and ask for that from the staff?

**Comment by baxgas** [comment]
@pvj OK, I'll ping them with "Just Do It" strategy.

**Comment by gammaw** [comment]
@baxgas cool! Can we show the tags in the Schedule view? If it's too dense, then on the all Shows page? Can you propose some drafts, maybe using screenshots of local versions?

**Comment by baxgas** [comment]
@gammaw Tags implemented:
![image](https://user-images.githubusercontent.com/36408851/97748174-56c11d80-1aed-11eb-9486-e8add4d5c670.png)
Is the **Tags:** text appropriate, or should we use some other title?

**Comment by gammaw** [comment]
@baxgas gastronomy :)

Or we just use rectangles like on NTS. It wouldn't be copying (I hope), the rectangle stlye is common way to show tags, or not?

![BE3953DF-6433-4983-9013-EC194B308592](https://user-images.githubusercontent.com/28865986/97802132-9d279100-1c41-11eb-8f94-d50a44a1b56e.png)

**Comment by baxgas** [comment]
Sure, nice idea, made it

![image](https://user-images.githubusercontent.com/36408851/97802693-8b47ed00-1c45-11eb-9cdf-0038bd548193.png)

**Comment by gammaw** [comment]
NICE!
Any plans we for showing tags on the home page too? Maybe the first 1 or 2 tags in the player, under the subtitle? Or in the schedule table? Or not at all?

**Comment by baxgas** [comment]
@gammaw I wouldn't put the tags in the player (remember we already had some overflow issues eg. with Csináltam neked egy...), but could be shown on the new, redesigned Schedule block? Eg. When we have the current show "blinking" OnAir, it could write out the Show details, and with that also the Tags?

**Comment by gammaw** [comment]
Ok, we can defer the decision on this (discuss it together). And how about an "all tags" view somewhere?

**Comment by baxgas** [comment]
Sure, good idea! Made the page template for it.
I think we should have a better title and text for it, no? Should we go online with this branch and push the PR team to work on the content?

![image](https://user-images.githubusercontent.com/36408851/98215974-bfbef000-1f48-11eb-8e7f-503370e4542f.png)

**Comment by gammaw** [comment]
Nice!

> Should we go online with this branch and push the PR team to work on the content? 

I would wait for the PR's team to fill the tags. Otherwise we may show an inconsistent view (some shows have tags some others don't). I will doublecheck with the "PR" right away!

> and work on this page also while it is not linked anywhere

Makes sense. How about having a special tag "All tags", maybe styling it a bit differently, and show it on each subpage? That would be an easy entry point for this page.

**Comment by baxgas** [comment]
@gammaw one more addition, on a specific Tag listing, show also the other Tags. Also, please advise for the text-copy, I'm total idiot for good text-definitions

![image](https://user-images.githubusercontent.com/36408851/98217906-6c9a6c80-1f4b-11eb-9dab-99bb1509b431.png)

**Comment by gammaw** [comment]
Nice!

> Also, please advise for the text-copy, I'm total idiot for good text-definitions

You're not! :)
Maybe "All Lahmacun tags"?

**Comment by baxgas** [comment]
OK, thanks, I put the tag title,  also changed the tag button background to back pink, so it covers the background

**Comment by pvj** [comment]
I just followed back on this while reviewing the PR. 

While I think we should go live with this I would keep this issue open and follow up on the "other tags" on the tags pages. 

First of all it's great idea! If I understand it correctly it would gather all the tags which could be numerous. Should we improve this and only get tags of the posts that we display. So basically "related tags." What do you think?

**Comment by gammaw** [comment]
We merged above PR so I'm closing this. We further discussions we can use https://github.com/mmmnmnm/lahmacun/discussions
