### ISSUE TITLE
Schedule on Home page more compact

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#162]
Have only the current day opened, the others closed, with option to click-open the lists

**Comment by baxgas** [comment]
TODO: make the days title clickable to open sub-items

**Comment by gammaw** [comment]
Looks good! I was thinking that an icon for open/collapse would be helpful. What do you think? I'm afraid some users would think of it, similar to News>>

**Comment by baxgas** [comment]
@gammaw OK, I'll do it at some point, but I think the close/open script so far could also go live, no?

**Comment by gammaw** [comment]
It's pulled on dev, you can check it out. @pvj what do you think (you as a neutral third :)), do we need markers for collapse/expand or is it intuitive as is?

**Comment by pvj** [comment]
I think either can be good option but we should aim to have the same rules /  markers as with News/read more... etc

**Comment by gammaw** [comment]
Yeah, makes sense. How about something like? "More news", "Click to expand"

**Comment by baxgas** [comment]
@gammaw @pvj  see this issue https://github.com/mmmnmnm/lahmacun/issues/184 the branch for ths issue got corruted, continuing there at #184
