### ISSUE TITLE
Create maintenance page

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#178]
@baxgas can you think of an easy way to add a "Lahmacun is under maintenance, please visit back later" page that we can enable on demand?

**Comment by baxgas** [comment]
@gammaw sure, it is a plugin that needs to be installed in wp-admin. I put the Seed prod coming soon on Staging, if it's OK we can put it also on live.
Could be something like this:
![image](https://user-images.githubusercontent.com/36408851/71802655-aa461480-305e-11ea-8045-a7908978f0a3.png)

**Comment by baxgas** [comment]
OK, done, installed the plugin, just need to turn it on when needed.

**Comment by gammaw** [comment]
Cool! @pvj can you use/test it when doing https://github.com/mmmnmnm/lahmacun/issues/194? It's a plugin, you'll see, I don't want to mention the name here :)
