### ISSUE TITLE
Improve player display on locked mobile screen 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#182]
![image](https://user-images.githubusercontent.com/28865986/71640877-c890c680-2c92-11ea-8116-e2eaa9a84926.png)

**Comment by baxgas** [comment]
@gammaw made script to push the title when played, on stop it clears back to the station name

**Comment by gammaw** [comment]
@baxgas wowwow

Do you think it's possible to add the radio's name too and maybe our logo?

![image](https://user-images.githubusercontent.com/28865986/71838718-c9be5b00-30b9-11ea-97b2-e53a22d023d0.png)

**Comment by baxgas** [comment]
Logo I don't think is possible, it is system logo of the app, apps like Music or similar can put the cover, but it is a different story.
Title I can add to the artist/title text, but wouldn't it be too long? I don't think it is needed

**Comment by gammaw** [comment]
@baxgas I see. Picture is out then. 

For the rest: what if we have "Lahmacun radio: [artist]"? I think it's good to display the brand. The "song title" is detail.

**Comment by baxgas** [comment]
@gammaw OK, the format is now: 
stationname: artist  – song

**Comment by gammaw** [comment]
@baxgas if I understand you solution the document title changes upon hitting play on the player. Wouldn't that mean that any changes on the player (e.g., new show) would not take effect on the lock screen?

**Comment by baxgas** [comment]
No it should update at any change in player json

**Comment by gammaw** [comment]
Are you sure? It's under "methods" and "play" in the Vue file. Isn't the update only triggered if play is hit?

**Comment by baxgas** [comment]
@gammaw thanks for pointing to this, I made the fix and committed, can go live.

**Comment by gammaw** [comment]
Very nice! 

But check this screenshot out. It's without any change on an Android phone with Chrome. All metadata including art work is updated and recognised!

This is done by these lines (original Azuracast code): https://github.com/mmmnmnm/lahmacun/blob/4acc484a0ac25ef5b11182503afee80347262386/wp/wp-content/themes/lahma_maker/assets/playerfiles/radio_player.vue#L406-L415 

I found this about the compatibility of the feature: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaSession

Which means that we're now building a workaround for a feature that should be supported as is :(
I'll enter an issue for Azura to ask if they plan to change their code for broader usability.

![image](https://user-images.githubusercontent.com/28865986/77232341-b98a2800-6ba0-11ea-8f1f-d6a1ebc3e0a4.png)

**Comment by gammaw** [comment]
Corresponding upstream issue: https://github.com/AzuraCast/AzuraCast/issues/2547

**Comment by baxgas** [comment]
Nice, thanks for searching this out. But anyway, generally changing the document title doesn't hurt, because people can see what's online eg. also in the browser window/tab-title

**Comment by gammaw** [comment]
@baxgas did you see this alternate solution: https://github.com/AzuraCast/AzuraCast/pull/2550/commits/1d9a13d250ac9fae13e5506e8c50aa8820639080#diff-aa93a7d5f1017f946f41af37bf7fc125

For me it seems to be functionally equivalent but for less overhead.

**Comment by baxgas** [comment]
@gammaw  no. but let's check it, great if it works!

**Comment by gammaw** [comment]
@baxgas did you check it, does it work? I see you added the lines but shouldn't we delete the lines in the `checkNowPlaying` function then?

**Comment by gammaw** [comment]
Oh I see you didn't include those lines in the branch you continued working on: https://github.com/mmmnmnm/lahmacun/tree/%23198-rework-menu

I tried with Safari, I don't see any effect of the change. Did it work for you?

**Comment by baxgas** [comment]
@gammaw you are right the Azura solution doesn't work :-( 
My solution did work though (it changes the document title which should work everywhere), should we go with it? https://github.com/mmmnmnm/lahmacun/commit/9f0ec113957eb7dfc1f0bc08eee4300006783b86

**Comment by gammaw** [comment]
@baxgas can you check what's the status now? What I remember is that it's good on Chrome but it looks poor on Safari.

**Comment by baxgas** [comment]
@gammaw both display the title of the page (which is open in the browser), so I think the best is to change the document.title (on play, stop, check_playing methods)
https://github.com/mmmnmnm/lahmacun/commit/9f0ec113957eb7dfc1f0bc08eee4300006783b86

**Comment by pvj** [comment]
This is very old, and I am sure we will need to make sure this works for mobile after rework. I can't quite capture all this technical details but I added an issue. @gammaw @baxgas can you please make sure to sort this out and close it?

**Comment by gammaw** [comment]
Thanks. It was a browser specific issue and it may be a different situtation with Nuxt so I would close it here and we'll see if we have any issue in the New World.
