### ISSUE TITLE
Refine Home page interaction

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#184]
Continuation from #162

**Comment by gammaw** [comment]
@baxgas I like the plus/minus thing a lot!

I'm still not sure about the News and news item part. Similarly to the plus/minus sign for the schedule, I think we would need something which is a clear sign even if you don't hover over it. For example a link "More news" somewhere near to News and "Details" somewhere near to ...

What do you think (also @pvj)? 

![image](https://user-images.githubusercontent.com/28865986/71905446-70f9cb80-3168-11ea-9536-7e188695a84a.png)

**Comment by baxgas** [comment]
More News could be OK, with the >> sign by Default. Anyway I didn't have problem with the News as it was, but it is maybe not so UX friendly as it turned out.

Btw. the girlfriend of Kollányi Bence is a UX-expert, maybe we could review the site with her?

**Comment by baxgas** [comment]
@baxgas like this
![image](https://user-images.githubusercontent.com/36408851/71933795-41b48000-31a3-11ea-908f-302c31030112.png)

**Comment by gammaw** [comment]
Thanks @baxgas!
