### ISSUE TITLE
[Liquidsoap] Influence order of playback in case of multiple tracks in playlist

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun#187]
Issue with playbacks happened in the past that were due to the playlist having more than one member. 

In the current configuration we always need to have only one file, the latest so the playlist plays that. If there are more than one members in this list the stream server will access the oldest, the first element and go in that order (this make sense for some radios working with playlists we however would like the opposite: regardless of old files, always just play the newest show, please!) 

This can probably fixed in our liquidsoap configuration. I can imagine one out of the 2 approaches could work: 

 * Playlist method should add members in reverse order and playlist access follows same logic
 * Playlist method adds members the same but playlist is accessed from the back (reversed in full accessed from front?)

**Comment by gammaw** [comment]
@pvj good point. Although it's not an intended use case yet, it would add a good protection in case we fail to delete old files. I don't know any Liquidsoap operator that would do that. I would post a question on their GitHub page. Btw, are you sure Liquidsoap selects the oldest files first?

**Comment by gammaw** [comment]
Is this related? https://github.com/savonet/liquidsoap/issues/1167

**Comment by gammaw** [comment]
Related: https://github.com/mmmnmnm/lahmacun/issues/227#issuecomment-619593959

**Comment by gammaw** [comment]
@pvj the alphabetical order would give us an easy way to adjust the order of play, the only problem I see is that AC may go mad if you just rename files in a folder. So we need to test it carefully once the new LS is available in AC (it's a recent LS commit, it should be in the next LS release, which still needs to be integrated by AC, so let's see).

**Comment by gammaw** [comment]
Important: https://github.com/mmmnmnm/lahmacun/issues/227#issuecomment-621032380

**Comment by gammaw** [comment]
Closing it as the parent issue has been closed too.
