### ISSUE TITLE
Remove news entry time stamps on home page

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#189]
... and keep it on:
- single new page and
- all news page (?) – we didn't discuss it but could make sense. Thoughts?

**Comment by baxgas** [comment]
I wouldn't keep it anywhere... it is not so important and could be strange also at other places (eg. NYE on Dec. 25)

**Comment by gammaw** [comment]
@baxgas hmm I'm not sure. It's very strange too not to know when a news item was created, no? It could be yesterday or months or weeks ago. What if we're careful with how we name titles (e.g., instead of having a news item "New Year's Eve Live Show" with time stamp Dec 28th we have "New Year's Eve Live Show Planned")? @pvj what do you think?

**Comment by gammaw** [comment]
No reaction, I'll close it until further input.
