### ISSUE TITLE
Submit Show

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#192]
Form Details: ( @gammaw @pvj – in Hung or Eng? )

> Formációd neve......................
> Honnan küldöd................(Bp, Nyíregyháza, stb)
> Genre.........................
> Linkek hozzád...........(fb, bandcamp, ytube, stb)
> Email cimed..............................
> + 
> beikszelendő kisnégyzet:
> tanusitom, hogy a beküldött zene az én saját szellemi termékem,
> hozzájárulok, hogy a beküldött adataimhoz a Lahmacun rádió szerkesztői hozzáférjenek
> és hozzájárulok, hogy a Lahmacun rádió anyagi ellenszolgáltatás nélkül lejátsza
> + 
> egy "nemvagyok robot" capcha
> +
> Beküld-gomb
> 
> >>> majd feljön egy köszipacsi üzenet

**Comment by baxgas** [comment]
TO-DO: 
- [ ] responsiveness
- [ ] Implement the Contact Form plugin on the live site
- [ ] Captcha v.3

**Comment by gammaw** [comment]
https://github.com/mmmnmnm/lahmacun/discussions/418
