### ISSUE TITLE
Update to AzuraCast 0.9.9

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#194]
- [x] Check Azuracast commits/releases: what features do we expect? 
    - [x] Streamers schedule time

Complete following checklist on **dev server**. 

- [x] Azuracast checks
    - [x] Upload media
    - [x] Edit media data (add art work, change title)
    - [x] Change playlist (e.g., add newly loaded media to off air)
- [x] Liquidsoap (LS) checks
    - [x] No errors/warning in LS logs
        - [x] Check if all playlists load their respective track(s)
    - [x] Radio starts and plays 
    - [x] Try if jingle is played between two off air tracks 
    - [x] Try live source 
        - [x] if it connects
        - [x] if the current music fades out before switching to live source
        - [x] if the front end looks ok
        - [x] if the the music fades back after disconnecting the live source
    - [x] Try scheduled show (hint: play with time in LS config)
        - [x] if it gets started
        - [x] if fading out off air music before works
        - [x] if fading in off air music after works

**Comment by gammaw** [comment]
Additional notes:
- Although [release notes](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.8.1) don't mention the fix of the fading issue (https://github.com/mmmnmnm/lahmacun/issues/150) [it seems](https://github.com/AzuraCast/AzuraCast/commit/2b631e03e0995efec5b1e49b457e686efef240d2) that they updated to the [Liquidsoap 1.4.1](https://github.com/savonet/liquidsoap/releases/tag/1.4.1) which fixes it
   - Quick fix (see [lines](https://github.com/mmmnmnm/lahmacun/blob/aa9b7e70e9e5a90772521b1585e3f5644f38c2ee/azuracast/liquidsoap_custom.liq#L292-L375) our custom LS config) should be deleted and tested if fading works
- Use above checklist for standard checks!
- Special check: listeners map registration (see Azuracast release notes)
- Further special checks: Apply changes display bug(https://github.com/AzuraCast/AzuraCast/issues/2262)

**Comment by gammaw** [comment]
@pvj when do you plan to do this?

**Comment by gammaw** [comment]
Issue renamed for latest Azura release: https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.9

**Comment by gammaw** [comment]
@pvj I see you tried scheduling a live streamer slot. It seems that Azura won't generate additional LS config for those schedules. Did you try what happens if you try to connect outside the scheduled time? Will Azuracast deny the authentication? Will Azura send a `false` response to the AzuraCast DJ Auth Response request (see [here](https://github.com/mmmnmnm/lahmacun/blob/a976ade4878eadb2fd96b842267bd01c643ce9a5/azuracast/liquidsoap_custom.liq#L279-L280)), or is it another way of denial?

**Comment by gammaw** [comment]
Just checked. Yes, if a time is scheduled for the streamer and the streamer wants to connect outside this time then the authentication will fail (`AzuraCast DJ Auth Response: false` message in the log). 
Important notes:
- No server restart is needed upon changing schedule times because it's an Azura side change which does not affect LS. 
- Streamer won't be kicked out when the scheduled time ends. The time window only controls when the streamer can connect.

**Comment by pvj** [comment]
@gammaw Sorry for not describing that earlier. Schedule is azura-side front-end only and connection is only rebuked if the flag is selected on azura's admin. If schedule is only set with no force-schedule set then it is more just like calendar entry and user is allowed to connect even outside scheduled time.
