### ISSUE TITLE
Add Mixcloud icon to menu

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#197]
@baxgas now that we have the nye show uploaded to mixcloud, could you add the mixcloud link to the usual place? I hope we won't have a space issue (too little space for one more icon, I remember we had to trick last time.)

**Comment by baxgas** [comment]
@gammaw ok, prepared the styles, menu item should have the `mixcloudmenu` class
![image](https://user-images.githubusercontent.com/36408851/74845228-f9a28480-532e-11ea-955e-86a1abc3ea0b.png)

**Comment by gammaw** [comment]
@baxgas <3
