### ISSUE TITLE
Install WP caching and minifying system to improve the loading speed?

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#199]
Not a "must" at the moment, but as our site grows, it would be good to keep the loaded files' size as small as possible. There are some Wp plugin solutions, see list:
https://athemes.com/performance/best-wordpress-caching-plugins/

They suggest W3 Total Cache, I also used it in many scenarios, works fine
https://wordpress.org/plugins/w3-total-cache/

**Comment by gammaw** [comment]
Not an issue at the moment, new website should handle it.
