### ISSUE TITLE
Show sub sub pages and dated post entries

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#205]
One show would like to post articles under their sub page. This could be a page like

/shows/show_name/sub_page_name

or a post like

/shows/show_name/2020/03/12/slug_name

It would be good to support both.

@baxgas can we do this?

**Comment by baxgas** [comment]
@gammaw that is the idea I was thinking about some time ago :-) Good if somebody writes good sub-posts, will get more visitors

If there are a lot of posts and individual content, it is better to go on sub-domain, eg. **showname.lahmacun.hu** if there will be just some occasionally we can make categories for **show_name** with individual titles with this structure **/shows/show_name/sub_page_name**

**Comment by gammaw** [comment]
Yeah, I remember :)
I would start with the second option. The subdomain is a bit too much for the moment. In my opinion at least. 
How about the post option with the date and the slug? Do you think we could support both?

**Comment by baxgas** [comment]
> How about the post option with the date and the slug? Do you think we could support both?

@gammaw personally I don't like the date structure, but if it has advantages why not, seems to work:
https://staging.lahmacun.hu/shows/mmn-blog/2020/03/12/my-first-post/

**Comment by gammaw** [comment]
Very nice! I think the date structure is a better fit sometimes. If it's more static content, then sub pages are better. Can we do both? 
And sure, this template will be good.

**Comment by baxgas** [comment]
> Can we do both?

No, it is fixed, and btw. it changes also the other link structures!

![image](https://user-images.githubusercontent.com/36408851/76599127-9f977800-6504-11ea-97e8-3a815d689a62.png)

![image](https://user-images.githubusercontent.com/36408851/76599172-b6d66580-6504-11ea-90e7-916b8549ff50.png)

**Comment by gammaw** [comment]
Oh I see. I remember that we use Post for shows too. But this won't be good. Show urls should not have dates in them. We can consider using Page for shows. Let's discuss this in person.

**Comment by baxgas** [comment]
I wouldn't make the mess to change it, let's make the **/shows/show_name/sub_page_name** version

**Comment by gammaw** [comment]
Ok. Do we need any change for that?

**Comment by baxgas** [comment]
No, it is the old one /%category%/%postname%/
https://staging.lahmacun.hu/shows/mmn-blog/my-first-post/

**Comment by gammaw** [comment]
Show host is not pushing, I'm closing it. We can reopen it if needed.
