### ISSUE TITLE
Test Butt 0.1.20

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#209]
See readme for Mac install. 
Also, post email questions on sourceforge. 
Butt site: sourceforge.net/projects/butt

**Comment by gammaw** [comment]
Looks good so far. @pvj if you have time before today's show you can install this version. User data is preserved across upgrades.

**Comment by baxgas** [comment]
@gammaw butt there is even a newer version, 0.1.28 (2021-02-07)
https://sourceforge.net/p/butt/news/

**Comment by gammaw** [comment]
Don't affect code, moved to Loomio.
