### ISSUE TITLE
Add link to Off Air show title + link more visible

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#212]
Link the album's or artist's page for the OffAir title (as the Show name to show page). Solve by custom field in Azura
Should be implemented also for these as a promo opportunity for submitters https://github.com/mmmnmnm/lahmacun/issues/192

Link in player better visible to distinct from the not-link titles  (maybe icon at the end, or different color?)

**Comment by baxgas** [comment]
Link has to be put in to the offairlink custom field for the show

eg. for QAD
![image](https://user-images.githubusercontent.com/36408851/78500464-d4d76480-7756-11ea-9446-a8e3fba3e3ac.png)

**Comment by gammaw** [comment]
@baxgas there is an issue with `check_offairlink`. If you enter a string and delete it later, then it's not `null` but an empty string. As a result, the icon will be shown without any URL. Maybe adding an additional condition to the check would fix it (`!== null && !==""`)? 

Another question: I just realized that we have SCSS in the Vue file. Is it something we inherited from Azuracast? Do you know if it's SCSS or plain CSS? If it's CSS then could have it in `style.css` as well, no?

**Comment by baxgas** [comment]
@gammaw good pointer, I added a condition checking the length of the string, which handles no character and empty space also. I reworked the icon a bit, so it is the same color as the sub-title, and changes to black on hover.

Yes, SCSS was just left in place from the original player, they give a basic setup our overrides are in the main style.css

**Comment by gammaw** [comment]
@baxgas thanks, we're getting there. I tested it and checked the code too. Two more questions (sorry): 
- **for off air music**: why do you check the empty string like this? `this.np.now_playing.song.custom_fields.offairlink.length > 3`. It's not a very easy to code and we won't remember it I'm sure (that it's a check for empty string). We can add a comment for sure but it would be even better to check the "real thing". I'm sure you had a good reason to check like this though. 
- **for scheduled shows**: we show the link even if it's the default URL (the show has no site). I know it's a corner case and it shouldn't be the case, but you remember that we had it with Bambusz for long time. Don't you think it would be good to check and only have a href/icon if it's not the default URL?

**Comment by baxgas** [comment]
> @baxgas thanks, we're getting there. I tested it and checked the code too. Two more questions (sorry):
> 
> * **for off air music**: why do you check the empty string like this? `this.np.now_playing.song.custom_fields.offairlink.length > 3`. It's not a very easy to code and we won't remember it I'm sure (that it's a check for empty string). We can add a comment for sure but it would be even better to check the "real thing". I'm sure you had a good reason to check like this though.
> * **for scheduled shows**: we show the link even if it's the default URL (the show has no site). I know it's a corner case and it shouldn't be the case, but you remember that we had it with Bambusz for long time. Don't you think it would be good to check and only have a href/icon if it's not the default URL?

my idea was also to check if it is a URL at all and not the length or similar. this maybe a good snippet
https://www.quora.com/What-is-the-best-way-to-validate-for-a-URL-in-JavaScript
Should I implement it?

**Comment by gammaw** [comment]
I think it's not necessary, it's us who enter things, we can trust ourselves :)
But if we delete the content in `offairlink` it becomes an empty string (not null), in which case we don't want to show the icon. My question is this: would something like this not work?

`this.np.now_playing.song.custom_fields.offairlink == ""`

I didn't get why you check for `>3`?

**Comment by baxgas** [comment]
It could work, but I thought it is safer to check for more characters, double-triple spaces :-)

**Comment by gammaw** [comment]
Oh I see. Yes your right, probably there is no valid URL which is less four characters :D

**Comment by gammaw** [comment]
> **for scheduled shows**: we show the link even if it's the default URL (the show has no site). I know it's a corner case and it shouldn't be the case, but you remember that we had it with Bambusz for long time. Don't you think it would be good to check and only have a href/icon if it's not the default URL?

@baxgas what do you think of that (from https://github.com/mmmnmnm/lahmacun/issues/212#issuecomment-622937948)? An idea would be to simple check if `show_url = homeServer`, if yes, we don't add a href.

**Comment by gammaw** [comment]
@baxgas did you have time to check it?

**Comment by baxgas** [comment]
It works as I tried in local, you just have to put an url here:
![image](https://user-images.githubusercontent.com/36408851/83962635-450d7e00-a89f-11ea-9262-d291389165a7.png)
