### ISSUE TITLE
Wordpress (and plugins) update

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#235]
I saw that there are many updates in our Wordpress. @baxgas can you do the updates? It's not urgent, I guess. I would do it first on staging, az ördög nem alszik.

**Comment by baxgas** [comment]
@gammaw made it on staging, works fine, should also on the live site.
btw, the maker parent theme has an update, but I think it is not worth to update, not many things changed, we have 0.3.5 and the most recent is 0.3.6
https://themes.trac.wordpress.org/browser/maker/0.3.6/README.txt?rev=125356

== Changelog ==
 
= 0.3.6 =
Fix: Appearance of Image captions on Image block.

(we adjusted already the Galleries on the Photos page)

**Comment by gammaw** [comment]
Thanks. As discussed, we skip updating Maker because we have no issue with it plus if we had one we could solve it ourselves. We can check their updates and update if necessary. Note: we cannot simply update from within Wordpress because the Maker plugin is in our GitHub repo (-> updates need to commit new files). 

Can you please delete the unused themes? Also, can you please update Charitable too? 

If all looks good, go ahead and update on prod too.

**Comment by baxgas** [comment]
I updated prod now, seems everything is fine.

**Comment by gammaw** [comment]
Thanks! Closing it now.
