### ISSUE TITLE
Sponsors page loads strangely

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#24]
Sequence: 
1. Go to /shows/lazy-calm-raga/ 
2. Click on Sponsors -> **it looks strange (aligned centered, see picture)**
3. Refresh sponsors page -> alignment will show correct

![image](https://user-images.githubusercontent.com/28865986/52013125-8e480380-24dc-11e9-9aa3-724372e2676e.png)

**Comment by baxgas** [comment]
fixed in 06666b0f672a93cdcbd8f38c84c0e2221066d000

**Comment by mmmnmnm** [comment]
@baxgas Nekem még mindig nem jó. Úgy nézem az a baj, hogy a body class-okat nem tölti be, amikor egy show-ról váltunk a Sponsors-ra (vagy akármilyen lapra aminek más a template-je), Be lehet azt valahogy külön tölteni?

Talán egyszerűbb, ha a DOM-ban egy alacsonyabb szintre rakjuk be a megfelelő classokat nem? A body class-jait nehézkesen tudnánk válatoztatni. Pont az a megoldás lényege, hogy az a rész nem változik refresh-re. Már ha jól értem.

**Comment by mmmnmnm** [comment]
@baxgas 

> felraktam az új centered templatet., majd a tartalomhoz igazítjuk ha kell
ennyi! kurva jó. nem is tudtam, hogy a parent theme template-jét is felül lehet írni

**TODO**: viszont ezt elvileg a fullwidth-re is akkor meg kéne csinálni nem? és a body class-ba visszarakhatjuk a dolgokat nem?

**Comment by gammaw** [comment]
seems to be fixed
