### ISSUE TITLE
Sponsors page logos nicer

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#242]
Smaller and more compact logos, in one row

**Comment by gammaw** [comment]
Did you change something already? I see them in one row already. 

I emailed Inclust now for a logo file so that we can make them black&white too.

**Comment by baxgas** [comment]
I didn't change anything but the Rogue Amoeba was inserted since, so it is nicer that the space is filled up. The logos could be a bit smaller though – let's wait for the new inclust and I'll make it.

**Comment by baxgas** [comment]
@gammaw added new template for targeting the sponsors page (has to be selected in wp also) and styling for images

**Comment by gammaw** [comment]
@baxgas it's on dev now. What exactly is the change about? I see that icons are smaller. Couldn't we just resize pictures in Wordpress for the same result? Why do we need a new template and CSS change? I'm sure I'm missing something, sorry for the silly questions :)
