### ISSUE TITLE
archived/ slug for archived shows

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#246]
@baxgas would it be possible to have a structure like /archived/archive-show-subpage? 
I know it's easy with Pages but since our show pages are technically Posts and not Pages, I'm not sure.

**Comment by baxgas** [comment]
@gammaw it should be done via Categories, so the Show pages can be "retagged" to the Archives category. Made it on staging, /category/archived/
Also prepared a template for it in the Shows branch https://github.com/mmmnmnm/lahmacun/commit/60f4eaf40a225096d32a93ff7c909f296e663a94

**Comment by gammaw** [comment]
@baxgas thanks. I was thinking of having it one level "deeper" such as /shows/archived/show-name. Is it possible?

**Comment by baxgas** [comment]
@gammaw OK, I made the page template for this. 
It will need a separate page, with name different than the shows category, or to rename the shows category (also in the template) so that they don't conflict. I would suggest the name `radio-shows` that would be linked from the menu. Of course this will need to be done in the prod site (db)

**Comment by pvj** [comment]
Sorry I  can't quite grasp this. Could you an example? Sorry! Thanks

**Comment by pvj** [comment]
Nvm got it on second read. `radio-shows` sounds good to me!

**Comment by baxgas** [comment]
@pvj I was just pointing to the fact that the category is called **shows**, so the page itself can't have the same name, either this-or-that needs to be renamed

**Comment by pvj** [comment]
Thanks I realised it after a second read. Didnt know that! I think your
naming is good and simple enough lets go with it.

**Comment by gammaw** [comment]
As we discussed today (IT meeting), let's go with implementing it in the shows category template so that we don't break the existing URL structure. fyi @baxgas

**Comment by baxgas** [comment]
@gammaw here it is: https://github.com/mmmnmnm/lahmacun/commit/e0d0e3f582c211cbd4b1588236b27250b5bf727a
sorry I didn't hash it for the branch

**Comment by gammaw** [comment]
Thanks @baxgas! Looks perfect. I merged and pulled on our live site.
