### ISSUE TITLE
Try alternate radio engines

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#248]
- Airtime: 
  - https://www.sourcefabric.org/en/airtime/
  - Note: pro version is licensed (https://www.airtime.pro/pricing/). 
- Mixlr
  - https://mixlr.com/priceplans/pro

FYI @pvj @baxgas

**Comment by gammaw** [comment]
We did a quick look at Airtime but couldn't figure out all the details (e.g., recurring show schedules).

**Comment by pvj** [comment]
Shouldn't we move this off of here to be honest?

**Comment by gammaw** [comment]
True, moved to L.
