### ISSUE TITLE
Show name in browser tab shows wrongly

### ISSUE THREAD

**Issue by mmmnmnm** [mmmnmnm/lahmacun#25]
Sequence: 
1. Got homepage. 
2. Go to any show via menu -> **show name in browser tab shows wrongly (see picture)** 
3. Refresh -> name will appear correctly. 

![image](https://user-images.githubusercontent.com/28865986/52013353-1dedb200-24dd-11e9-9f23-e0eac6a307a8.png)

**Comment by baxgas** [comment]
fixed in 06666b0f672a93cdcbd8f38c84c0e2221066d000
