### ISSUE TITLE
Add overflow only to content area to avoid double scrolls

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#259]
Now it is like this when Shows is opened

![image](https://user-images.githubusercontent.com/36408851/85839161-ddaa6600-b79a-11ea-8394-467a56207b0a.png)

**Comment by gammaw** [comment]
@baxgas having the new shows page, do we want to keep this content area? See https://github.com/mmmnmnm/lahmacun/issues/224

**Comment by baxgas** [comment]
Not needed, since the separate Shows page
