### ISSUE TITLE
Delete Wikihow show

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#265]
Git:
- frontend (php)
- backend (liquidsoap):
  - playlist definition 
  - transition (jingle)
  - timed schedule 

Test (on branch):
- pull it on dev (frontend + backend)
- streaming server: 
  - replace api keys w/ script 
  - restart docker (restart on admin page not enough)

**Comment by baxgas** [comment]
@gammaw OK, I prepared everything, but can't test now, don't have access from this computer

**Comment by gammaw** [comment]
@baxgas thanks. I think that the deletion in line 343 is wrong. The "Wednesday block" is between lines 327-334 and this is where the deletion should be. 

FYI: The transition "#ambient: Muto - Eastern" on line 335 corresponds to line 399 where the "off_air_ambient_mix" playlist is specified as an ambient fallback in case of gaps in the Wednesday afternoon programme.

**Comment by baxgas** [comment]
@gammaw ok, sorry, I quite don't get the new LS config stuff. fixed it now according to your guide

**Comment by baxgas** [comment]
@gammaw I pulled the stuff on dev, and it is now on the wikihow delete branch, can I make a merge-request to the master?

**Comment by gammaw** [comment]
@baxgas the LS config looks good now! Thanks. Before we merge it into the master, can you test the deployment of the new LS config on dev? 

I sketched the workflow in my first comment in this thread. Here is a reminder [from our wiki](https://github.com/mmmnmnm/lahmacun/wiki/About-Lahmacun's-%22Auto-DJ%22-(Liquidsoap)-configuration) for the Azuracast server restart:

> Azuracast needs to be shut down (docker-compose down) and launched again (docker-compose up -d).
