### ISSUE TITLE
Dynamic schedule table

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#297]
Highlight and Display infos about the active Show: 
Episode name, Tags, Cover

Next Show: episode name

Otherwise list with the usual infos: Playtime, Title, Archive - linking to arcsi section

**Comment by baxgas** [comment]
**Technology for solving this task:** 
Rework the Schedule table to vue dynamically loaded (?)
- have a local json with the shows list -> show day/nr. of day in the week, start/end time, title, link, archive-link
- loop the shows in table-rows, with sorting by nr.-of-day/time, if archive-link - show archive+link, add date to days
- check onair-show from streaming .api -> if onair-show == show in the list, add OnAir element + add class for blinking for the element

++ benefit, add a different sorting method (calendar view) for the generated table, as was noted a few times it has a better overview
++ will be better for updating the current order of the elements if day changes without reload of the page

**Comment by gammaw** [comment]
@baxgas good plan! You can go ahead implementing it. For the local JSON you can use a sample file with some test shows. Arcsi will provide the complete data (API yet to be added on arcsi side).

**Comment by pvj** [comment]
I will now close this captured the important design related ideas over at our issue tracker for the rework proj
