### ISSUE TITLE
More flexible banner for general announcements

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#302]
Our current donate banner is flexible about the text but the DONATE IS is always visible. Can we change it so that
1. the button can be disabled and
2. the text and hyperlink of the button is configurable? 

Background: in situations such as unstable coverage we can place an announcement.

**Comment by baxgas** [comment]
@gammaw OK, implemented, made a Pull Request

**Comment by gammaw** [comment]
Great job @baxgas! Thanks a lot. The feature will be very handy for service announcements. 

FYI @pvj
