### ISSUE TITLE
Bigger News item picture on front page

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#317]
This would be a "facelift" by simply changing the thumbnail view of the News items on the home page. E.g., we only the title and the image (in big!) but not the (truncated) text.

**Comment by baxgas** [comment]
I made something like this (first is always full width, others are smaller):
![image](https://user-images.githubusercontent.com/36408851/98160318-530f0b80-1ede-11eb-836f-a38d828f0473.png)

Should I make the main News section also in this style? ( ../category/news/  )

**Comment by gammaw** [comment]
@baxgas I like it!

> Should I make the main News section also in this style? ( ../category/news/ )

Not necessarily. 

Just did a quick test locally, the result was this. Is it a corner case when the first news item's picture is too narrow? 

![image](https://user-images.githubusercontent.com/28865986/98217020-2abcf680-1f4a-11eb-89e6-6598b8db8976.png)

**Comment by baxgas** [comment]
@gammaw 

Sorry, I didn't mention this in the post, but the thumbnails need to be regenerated for this, because of the new size. This is the plugin for it
https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by gammaw** [comment]
Thanks! I guess the problem was in the above case that the original picture was too small and WP couldn't scale it as needed. I replaced it with a high-res one and it worked nicely. 

I'm fine with it as it is, maybe one more comment: don't you think that the black & white caption is a bit too drastic ("funeral-like"?)? Writing on the picture could be a solution but it's tricky general because of the colors. Maybe if we use a blurred background under the text (with transparency), but I can imagine that it's not easy to do. What do you think?

**Comment by baxgas** [comment]
Yes, that was my initial idea, but then forgot to mess with it until that point. Something like this? Hope it works with every image, should be fine.

![image](https://user-images.githubusercontent.com/36408851/98298581-8755fb00-1fb6-11eb-8cb4-2e532e295e5e.png)

**Comment by gammaw** [comment]
Nice! Just asked Zs, she liked the bigger picture approach in general but she wasn't sure about the details. We messed around a little bit, left-aligned the text, used black text as this is our text color on the website, used the lemon color for the transition, and lowered the intensity/darkness of our standard purple. It's just a late nite pitch, I don't know if it makes sense. 

![image](https://user-images.githubusercontent.com/28865986/98301054-7effbf00-1fba-11eb-80ea-d19c5f9a1da2.png)

**Comment by gammaw** [comment]
New website will handle this.
