### ISSUE TITLE
Show archive filtering

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#329]
TODO: filter based on `archived` flag in `item` object. @baxgas feel free to close this issue if it's done already in https://github.com/mmmnmnm/lahmacun/issues/254

**Comment by gammaw** [comment]
Seems to be done already, see: https://github.com/mmmnmnm/lahmacun/blob/cb5199b6c9d28740a2ce76caac82174595aa3a74/wp/wp-content/themes/lahma_maker/template-parts/content-arcsi.php#L45

FYI @pvj @baxgas

**Comment by gammaw** [comment]
O I forgot. It's still a todo to check if there is at least one archived item, otherwise don't show the arcsi header at all. I'll check this.

**Comment by gammaw** [comment]
@baxgas can you check above change if you think its ok?

**Comment by baxgas** [comment]
@gammaw which cases did it fix, is it already on staging?

**Comment by gammaw** [comment]
@baxgas 

> which cases did it fix

If there is a show with items in arcsi but if the archived flags are all false, then you would still print the header for the archived block. 

Background: your code always returns `has_archive` true if there is at least one item in the items list. It's because the "archived" string that you use for comparison always translates to an integer 0 (see https://stackoverflow.com/questions/672040/comparing-string-to-integer-gives-strange-results). 

> is it already on staging?

No, it's on branch 329. You can use `git show` to check the commit the server is on.  

I'll do a PR to branch 254 when you approve the change here.
