### ISSUE TITLE
No picture & link when special chars in subtitle

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#330]
When only "Bábeli technikák" is used as a subtitle, things got normal again. 

![image](https://user-images.githubusercontent.com/28865986/100260445-b0303700-2f49-11eb-84cf-c5dddd0fb88e.png)

**Comment by gammaw** [comment]
Probably the same one:

![image](https://user-images.githubusercontent.com/28865986/114778874-b5b1e080-9d75-11eb-9eb7-b35dc1670c31.png)

**Comment by gammaw** [comment]
Being an upstream issue (seems so) the only realistic chance I see is to fix it on the arcsi side (since we normalise their anyways). What do you think @pvj?

**Comment by pvj** [comment]
> Being an upstream issue (seems so) the only realistic chance I see is to fix it on the arcsi side (since we normalise their anyways). What do you think @pvj?

I don't really like the idea of changing the user input too much but of course some sanitisation is needed. Yeah, I'd say it is an issue we can (will) handle on our side. I say we close this.
