### ISSUE TITLE
Refine arcsi frontend

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#364]
- grids are not in equal rows
- make cover image clickable for lightbox (scripts.js)
- add preloading wheel for listen button
- add reverse order of items change via js

**Comment by baxgas** [comment]
@gammaw - please review this and merge to arcsi frontend if ok

**Comment by gammaw** [comment]
@baxgas wow! Amazing stuff. Good idea on the reverse listing feature, and also a very smooth UI with the new spinning wheel transition. And the lightbox which started the whole thing. Thanks in the name of arcsi ;)
PR-ed and merged.
