### ISSUE TITLE
Integrate D23

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#368]

**Comment by gammaw** [comment]
@baxgas I did the following:
- reverted the merge commit on master and pulled it on prod frontend -> D23 disappeared in the schedule
- re-created a branch for the new D23 show
- committed a change to the LS config with the missing transition

The branch can be merged after Saturday, pulled on prod frontend and pulled & "activated" on prod streaming. 

FYI @pvj

**Comment by baxgas** [comment]
@gammaw thanks! I'll integrate it to the master now
