### ISSUE TITLE
Check js vulnerability in maker parent template 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#38]
![image](https://user-images.githubusercontent.com/28865986/52871433-55e62d80-314a-11e9-9223-53f81edef172.png)

**Comment by gammaw** [comment]
@baxgas Bár azt írják a 3.0.2-ben fixelve lett valami vulnerability, és a maker 3.0.4-et használ https://github.com/jshint/jshint/issues/3295

**Comment by gammaw** [comment]
![image](https://user-images.githubusercontent.com/28865986/52871531-8cbc4380-314a-11e9-89e9-030cde0a0d52.png)

**Comment by gammaw** [comment]
https://docs.themepatio.com/maker-upgrade-0-3-0/

**Comment by gammaw** [comment]
@baxgas van valami ilyesmi a dependenciesben  "minimatch": "^3.0.2", nem nagyon értek hozzá, de lehet hogy ez valami olyasmi hogy "3.0.2-es verziótól". lehet a github ezt értelmezi félre? majd egy nyugodt időben meg lehet próbálni ezeket simán csak átírni 3.0.4-re a json-ban, nem hiszem hogy nagy problémát csinálna, de nem árt letesztelni sem

**Comment by baxgas** [comment]
I think this .json needs to be generated on the server for the package. Some kind of version change track-keeping.
https://docs.npmjs.com/files/package-lock.json

For the symbols see: 
https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/

**Comment by baxgas** [comment]
Search/replaced in this commit: dcd485b066c2b2a3534f05bca385659f5746a7a5 for a quick-fix

**Comment by gammaw** [comment]
> Search/replaced in this commit: dcd485b for a quick-fix

@baxgas What do you mean? It was my commit.

**Comment by gammaw** [comment]
I'll close it for now.
