### ISSUE TITLE
Add Arcsi google tracking for listening and download

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#385]
Add Show name also to Listen trigger
Add Event for the Download

**Comment by gammaw** [comment]
Thanks @baxgas for adding this! Please, every time you add a new issue, don't forget to assign the project, a milestone (if applicable), and a label (e.g., bug, analytics, etc.).

**Comment by baxgas** [comment]
As agreed with @gammaw we make this structure for all
gtag
'event', 'Arcsi download',  (Arcsi Play || Arcsi Stop || Stream Start || Stream Stop)
'event_category': showName,
'event_label': epsiodeName,

**Comment by baxgas** [comment]
@gammaw ok, fixed it to the desired format, it is on staging now

**Comment by gammaw** [comment]
@baxgas wrong event name on arcsi stop: 

![image](https://user-images.githubusercontent.com/28865986/113520720-7c1eef80-9595-11eb-9812-1e496b61d3e2.png)

**Comment by baxgas** [comment]
It's the value - > if Play, value: 1 if Stop, value: 0
see at the stream player gtag it is also like that there

**Comment by gammaw** [comment]
@baxgas yes, you're right! I was acting too fast and didn't think of that the event name is a general one. Sorry & thanks!
