### ISSUE TITLE
Blocking load when arcsi hangs

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#386]
Hint: via timeout?

**Comment by baxgas** [comment]
https://css-tricks.com/snippets/php/check-if-website-is-available/

**Comment by gammaw** [comment]
@baxgas can you check what makes the frontend home hang when arcsi hangs? There are two cases: 
- arcsi **down** -> everything is good, the upper fix handles this case nicely on the show pages; 
- arcsi **hangs** -> the entire radio page is unavailable (home & show pages etc.), it's loading for a while and then it returns a 504 error. 

What's the arcsi resource that's causing it on the home page (I mean the landing page of the radio)? Any idea?

**Comment by baxgas** [comment]
@gammaw 
arcsi hangs -> I believe it sees the arcsi json exists, try to load, but fails when reaching timeout. 
could there be some error checking on server side, when something is wrong don't send anything, Headers etc.?

**Comment by gammaw** [comment]
> arcsi hangs -> I believe it sees the arcsi json exists, try to load, but fails when reaching timeout.

@baxgas can you point to the code where it happens? Again, we're talking about the home page, not about the show sub pages. 

fyi @pvj

**Comment by gammaw** [comment]
We should revisit the functionality. It works well when arcsi is down (docker is down) but not if we have the infamous arcsi hangs case (docker is up and arcsi in "live lock"). In the latter case, the frontend hangs too. 

FYI @pvj

**Comment by pvj** [comment]
Yes, needs to be fixed on the frontend for sure.

**Comment by gammaw** [comment]
Status: https://github.com/mmmnmnm/lahmacun/pull/420
