### ISSUE TITLE
Long subtitle of show display strangely on mobile

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#39]
![image](https://user-images.githubusercontent.com/28865986/53111301-2023b900-353d-11e9-90a6-25284a265fea.png)

**Comment by baxgas** [comment]
Fixed in 7a755c4c8a7fba2795dfb9588aebb7693d1f19d9

**Comment by gammaw** [comment]
Fixed by @baxgas by 7a755c4c8a7fba2795dfb9588aebb7693d1f19d9
