### ISSUE TITLE
Show date in news post page

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#399]
Single news post page doesn't have time stamp. We had some confusing requirements in the past why not to have it, but I guess those are obsolete. 

fyi @baxgas @pvj

**Comment by baxgas** [comment]
@gammaw I see it was missing from the News end-page itself, added it there

**Comment by gammaw** [comment]
Nice! Ready to PR?

**Comment by baxgas** [comment]
@gammaw ok, pull request added
