### ISSUE TITLE
Standalone Liquidsoap test environment

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#424]
Idea: we could simply use our new Liquidsoap Dockerfile (https://github.com/mmmnmnm/lahmacun/blob/%23351-once-operator/liquidsoap/docker-azuracast-radio-main/Dockerfile) and mount our custom Liquidsoap file into the image. 

Will try out soon and try to continue working on https://github.com/mmmnmnm/lahmacun/issues/422 in a local instance. 

Disclaimer: this issue is not yet about decoupling Azuracast for our prod setup (it's more a dev tool at the moment) but the knowledge can help us when we'll start to develop things along those lines.

**Comment by pvj** [comment]
I want in on this too!

**Comment by gammaw** [comment]
Seems to be working as outlined above. Did a draft how-to Wiki document to explain how it works: https://github.com/mmmnmnm/lahmacun/wiki/DRAFT:-Local-Liquidsoap-setup-(for-development)

**Comment by gammaw** [comment]
Liquidsoap audio stream running in local browser!! :)

Draft description updated with new steps (`output.harbor` for test and local playlists and audio files mounted into the Liquidsoap container): https://github.com/mmmnmnm/lahmacun/wiki/DRAFT:-Local-Liquidsoap-setup-(for-development)

![image](https://user-images.githubusercontent.com/28865986/126818868-fc3e8a2c-f291-4229-81bc-47d1c3fab315.png)

**Comment by gammaw** [comment]
I was afraid of this, that Azuracast will have a problem of using the new `stations` image. Indeed, we have the following errors: 
- The `web` container throws this:

```
web_1                      | In CompiledContainer.php line 557:
web_1                      |                                      
web_1                      |   Could not connect to supervisord.  
web_1                      |                                      
web_1                      | 
web_1                      | sync:run [<task>]
```

- The `stations` container throws this: 

```
stations_1                 | Warning: illegal backslash escape in string.
stations_1                 | At /usr/local/bin/my_init, line 31, char 29:
stations_1                 | Error 3: Syntax error!
stations_1                 | [WARN  tini (6)] Tini is not running as PID 1 and isn't registered as a child subreaper.
stations_1                 | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
stations_1                 | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
```

I will look into this, until then the last working solution is where we build the Liquidsoap image from the source.

**Comment by gammaw** [comment]
Additional comment for last commit: for some reason the `stations` service with the new Docker hub Liquidsoap image starts with the command `/usr/bin/tini -- /usr/bin/liquidsoap /usr/local/bin/my_init` (see screenshot via `docker container ls --no-trunc`). Before the Dockerfile change (e.g., in 75c057d93e266fd7fff02c7b444cbabf0f01b7e9) it was only `/usr/local/bin/my_init`, which worked fine (no nasty errors like above). To mimic the old behavior, I forced now to run this script (and this script only). Not the nicest fix but it works. 

Note: Tini is an init mechanism used by Docker and by Tini's convention `/usr/bin/liquidsoap` and `/usr/local/bin/my_init` are params for the Tini process. I can imagine that the Liquidsoap image kind of forces this behavior, which has now been overridden by an explicit entrypoint (see second screenshot). 


![image](https://user-images.githubusercontent.com/28865986/129165436-bd9536c0-1093-4063-a20b-885730cb8825.png)

![image](https://user-images.githubusercontent.com/28865986/129166419-08a6b7d6-785b-416c-a432-0479f19d7096.png)

**Comment by gammaw** [comment]
Seems stable, also for live. Details: https://github.com/mmmnmnm/lahmacun/wiki/Local-Liquidsoap-setup-(for-development)
