### ISSUE TITLE
Add Schmerz Show to radio

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#425]
- [x] make a show page
- [x] ask for a review of the show page from the host
- [x] make arcsi section
- [x] make azuracast section
- [x] modify liquidsoap and schedule blocks in a branch
- [x] ask for a PullRequest Review
- [x] pull on frontend
- [x] pull on streaming & restart
- [x] inform comm team for promotion
- [x] upload first episode
- [x] enter to shows list
- [x] enter to membership list
- [x] add to calendar
- [x] add to newsletter
- [x] 🚀

**Comment by gammaw** [comment]
@baxgas I added the missing todo items to the list. I hope it's complete now but please check. 

I finished the todos that are needed for tomorrow's start (pull on frontend, pull/restart on streaming, inform comm). 

FYI @pvj
