### ISSUE TITLE
Fix inconsistent ismobile check

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#43]
**Issue**: currently is_touch_device() is used to detect if device is mobile or not (see /wp/wp-content/themes/lahma_maker/js/scripts.js). On a high-resolution Lenovo laptop without touch it detects that it's a "mobile" device. As a result, the volume control is not shown.

**Comment by baxgas** [comment]
Replaced with modernizr detect in 7a755c4c8a7fba2795dfb9588aebb7693d1f19d9
