### ISSUE TITLE
It's Alive NYE frontend/Liquidsoap changes

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#457]
Branch https://github.com/mmmnmnm/lahmacun/tree/prog/szilvesztro-2021 (won't be merged into master) includes:

- [x] Frontend changes
- [x] Liquidsoap changes

**Comment by gammaw** [comment]
There will be no PR for this branch (as it won't be merged) so please review it here. Frontend (static HTML) and Liquidsoap changes have been added to the branch.

**Comment by baxgas** [comment]
Looks fine to me

**Comment by gammaw** [comment]
There was a bug unfortunately which I noticed when deploying it but now with the fix it seems to work and it's on prod.

**Comment by pvj** [comment]
Looks great! Thank you!

I think just in case to make it easier to find this branch of the code we should tag (`git tag -a v2021.nye -m "specific head for NYE"`) the branch head. It would be easy to use it as a starting point for other one off events perhaps?

I've added this right now for your branch, I hope you don't mind. You can see it by running `git tag`

**Comment by gammaw** [comment]
Cool! I'm not sure how reusable such a branch will be, as it's day and schedule specific (names, times, transitions etc.) but it's for sure a nice souvenir in our repo!

Did you push the tag already? I cannot see it yet.
