### ISSUE TITLE
Add European Labs to Schedule

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#462]

**Comment by gammaw** [comment]
Thanks for adding it! I'm closing it

**Comment by gammaw** [comment]
Reopening as we I can use it for the Liquidsoap changes

**Comment by gammaw** [comment]
@baxgas I added the Liquidsoap changes, please check if it looks good to you too. I'll deploy it these days to make sure that there is no syntactic error.  

PS: @pvj sorry for the assignment madness, I misclicked.

**Comment by pvj** [comment]
No worries I was happy to quickly check myself. Did not find issues w/ your changes!
