### ISSUE TITLE
Not all shows appear on the showsList

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#50]
@baxgas see issue title

**Comment by gammaw** [comment]
**Root cause**: posts array only contains the posts displayed per page (compare with `$found_posts` attribute of query which is the number of _all_ posts matching the query - see documentation below). 

**Workaround**: set high number of number of posts displayed per page in the WP settings (/wp-admin/options-reading.php). Note that we use posts as pages so this settings has no effect on the public page. 

**Solution**: collect all posts independent of WP settings.  

Shows list processing PHP: https://github.com/mmmnmnm/lahmacun/blob/master/wp/wp-content/themes/lahma_maker/showslist.php
WP_Query documentation: https://codex.wordpress.org/Class_Reference/WP_Query

**Comment by baxgas** [comment]
Added 'posts_per_page'=>-1 to the query, which gives all the posts. Fixed in f6b04469204f9addcf3c1c55cf64922b914e0ec2

**Comment by gammaw** [comment]
@baxgas just tested and still see 10 shows in the list if 10 shows per page are set in WP
