### ISSUE TITLE
Set up new VPS for performance test

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#62]
VPS options: 
- https://www.arubacloud.com/ Seems to have good prices. How about backup? 
- Digital Ocean?

More complex cloud options: 
- Amazon (AWS for VPS + S3 for backups?)
... 

Related issues: 
- https://github.com/mmmnmnm/lahmacun/issues/56
- https://github.com/mmmnmnm/lahmacun/issues/51

**Comment by pvj** [comment]
we have a test-DO now here 46.101.106.153

I may also allocate an ECS that we may use for the azura + lahma_wp containers

**Comment by gammaw** [comment]
@pvj let's test the new server how it's running for a couple of days before we close this.
