### ISSUE TITLE
New look w/ news and daily schedule

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#63]
@baxgas @pvj start chat here, Hungarian is also fine :)

**Comment by baxgas** [comment]
We should implement something like this:
![Lahmacun-home-mockup](https://user-images.githubusercontent.com/36408851/55874587-14469180-5b93-11e9-9bfc-01df6a69bf4f.jpg)
For this I would need Advanced Custom Fields plugin, with the custom fields setup for the show schedule (day/time) and News Category in Wp-db. Other setup will be in template through git (reworked home-page template, looped News and Shows with custom sorting)

**Comment by gammaw** [comment]
@baxgas I would say go ahead and install them. We should have a list of required plugins that need to be manually installed in any wordpress instance. You can use the test server for live tests and your local copy for pre-tests, can you?

**Comment by baxgas** [comment]
Added the News and Schedule on the intro page in 290e797852dfcecd17cf6c6f94013132b5b7d1fd (fixed ajax in b98277bf46f1314a82f310e493cfe83d10b0787c)

Some notes:

**NEWS**
Need a "News" Category with posts. Shows 3 posts on the home page, and lists all the posts on a Category sub-page

**SCHEDULE**
Inserts a page named "Shows-lister" in the main page (
![image](https://user-images.githubusercontent.com/36408851/56795864-9f6d8b80-6811-11e9-9248-4a3845bffaab.png)
)
Page starter contents is in the commit under filename "Shows-lister.html", with the correct syntax and styles. Can be edited in wp-backend
![image](https://user-images.githubusercontent.com/36408851/56795936-d93e9200-6811-11e9-82a7-0bbf9ad8e0ce.png)

**TODO (???)**
Make the Schedule listing automatically based on ACF custom fields. Could not make the correct sorting by day/time. The draft is in template file "loopshows.php", the ACF setup is in "acf-shows.json"

**Comment by gammaw** [comment]
@baxgas I deleted the Open news item link (70bc35e2244bed254cbeb67724fc3ed0513a4e2d) because the news item is a link anyway. 

Would it be possible to add the date of publication for news item?

**Comment by baxgas** [comment]
OK, sure, the date can be implemented.

**Comment by baxgas** [comment]
> @baxgas I deleted the Open news item link (70bc35e2244bed254cbeb67724fc3ed0513a4e2d) because the news item is a link anyway.
> 
> Would it be possible to add the date of publication for news item?

OK, fixed in c2dde055953a4d41a2427ab7b57c97b7f14e731b but I couldn't find your fix of Open news link, removed it anyway, instead (...)

**Comment by gammaw** [comment]
> OK, fixed in c2dde05 but I couldn't find your fix of Open news link, removed it anyway, instead (...)

@baxgas yeah probably I didn't push the commit, I had conflict, resolved it somehow, how the link is back. Maybe it's a sign so I kept it :)

Looks good. I think: 
- we can delete "Posted on:" and write the date in italics (to show that it's metadata),
- I would get rid of the Hungarian days, we don't translate a lot of things.

**Comment by baxgas** [comment]
OK, made the posted on in 628d8b291b7ed4a0842217e7fd010e3b08724d84
The schedule data (for Hungarian days) is in db / wp-post editor, has to be changed there

**Comment by gammaw** [comment]
Released here: https://github.com/mmmnmnm/lahmacun/releases/tag/0.1_release_candidate
