### ISSUE TITLE
Figure out vue build process

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#73]
See this thread for hint: https://github.com/AzuraCast/AzuraCast/issues/1472

Set severe because Azura's Vue player adds connection lost detection.

**Comment by gammaw** [comment]
@pvj I checked carefully what the Azura guys were suggesting and it starts making sense to me. Some observations: 
1. Vue files can indeed be built using Webpack. -> We can concentrate on using Webpack (looking at examples, e.g., https://medium.com/front-end-weekly/webpack-by-example-part-1-1d07bc42006a).
2. Webpack always needs a configuration. -> Following the hint in the Azura issue, the corresponding Webpack config is embedded in the Gulp config file: https://github.com/AzuraCast/AzuraCast/blob/6bf1434a1cef0efd4c6537c1fea5928a121e4d7c/web/static/gulpfile.js#L226-L250
3. A package.json is always needed in this type of setups, I guess we can use them: https://github.com/AzuraCast/AzuraCast/blob/master/web/static/package.json

**Comment by gammaw** [comment]
@pvj another hint: above package.json helps also to see what dependencies we need to install. And here is a tutorial which helps with Webpack + Vue: https://www.freecodecamp.org/news/getting-started-with-vue-single-file-components-using-webpack-2ae078058688/

**Comment by gammaw** [comment]
Just managed to build it using npm/npx. I have these files in one folder: 
- webpack.config.js containing above lines from Azura's Gulp config (needed to adapt the syntax a little bit),
- package.json from Azura (find it next to Gulp config file) without the Gulp lines (I'm sure we can remove more),
- radio_player.vue.

Run 'npm install' (to install dependencies based on package.json) then 'npx webpack radio_player.vue'. 

Will commit some code soon.

**Comment by gammaw** [comment]
Getting closer I guess: 7631b0751913acf093889dadbf72fc0341b13200
Current status is deployed on dev

**Comment by gammaw** [comment]
This is how you can build the main js (radio-player.js) locally: 
1. Go to `/wp/wp-content/themes/lahma_maker/assets/playerfiles/`.
2. Run `npm install`. This will locally install the build dependencies into a `node_modules` folder -> add to gitignore list. 
3. Run `npx webpack radio_player.vue`. This will build the js file. 

Prerequisites: Node.js needs to be installed on your machine.

**Comment by gammaw** [comment]
@baxgas we can use this issue for the frond-end adaptation topics as well (we can later change the title)

**Comment by gammaw** [comment]
@baxgas the linked css and js files in `playercode.php` are currently hosted by Azuracast but they are either
- css files (e.g., light-7708c1e378.css) that we can define ourselves (depending on how we want to brand the player) or
- external references which you find in your local `node_modules` directory after you run `npm install`. We should host them similar to `radio_player.js` under `assets`. By the way, I'm not sure we need them all, we should check which does what.

**Comment by baxgas** [comment]
OK, fantastic, thanks @gammaw ! 
I styled the player, it is on commit a542416ac7eae556c571f611b2fc38a29f6a57e4
Please check on dev if the sorting script works as intended

**Comment by gammaw** [comment]
@baxgas player looks good! Unfortunately, sorting doesn't work and dates are missing.

**Comment by gammaw** [comment]
@baxgas thanks for 2164d65c9b40b360b896d73875d30d2d41ebaac9 it works now!
Some comments: 
- What is `altalanosinfok` in the vue file? 
- In playercode.php we now have `now_playing_uri: 'https://dev.lahmacun.hu:8084/api/nowplaying/1` which I think would not work for prod. Do we need the "old solution" here? 
- I guess following block for song history can be deleted. Also, it seems that `bootgrid` is being used by this block. Can we get rid of the `bootgrid` dependency after removing this?  https://github.com/mmmnmnm/lahmacun/blob/2164d65c9b40b360b896d73875d30d2d41ebaac9/wp/wp-content/themes/lahma_maker/playercode.php#L57-L128

**Comment by baxgas** [comment]
> What is altalanosinfok in the vue file?
I had to add some classes in the vue to make better style targeting

> In playercode.php we now have now_playing_uri: 'https://dev.lahmacun.hu:8084/api/nowplaying/1 which I think would not work for prod. Do we need the "old solution" here?
Good point, I didn't check the js part of it, but sure, we need to fix that. Should we go the old $server php check to see where it is hosted?

> I guess following block for song history can be deleted. Also, it seems that bootgrid is being used by this block. Can we get rid of the bootgrid dependency after removing this?
I wouldn't take it out, maybe it breaks the player? Also, don't we need the song history in nowplaying json?

**Comment by gammaw** [comment]
Vue change: ah ok, so it's functional and we need it and use it. Happy to hear that we have built the vue file after custom change.

Nowplaying uri: yes, I would do it that way. Otherwise we need to change it manually.

Song history: I would remove it and check if the player breaks. I don't think so it would.

**Comment by baxgas** [comment]
OK, added the Stream Server Checks in 2164d65c9b40b360b896d73875d30d2d41ebaac9
