### ISSUE TITLE
Check backup server option

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#95]
What startup, what service? Is it an option for us?

**Comment by pvj** [comment]
The original data versioning tool that I heard about wasn't easy to find as there are now some other options in this field. Not many but still, we can evaluate which would be best for our purposes of archival. 

Will comment on these later but wanted to first share findings: 

- https://git-lfs.github.com/
- https://dvc.org/
- https://www.pachyderm.io/

Pachyderm was the one I mentioned initially.

**Comment by pvj** [comment]
This runs on IPFS but I'll also review it: https://github.com/qri-io/qri

**Comment by gammaw** [comment]
@pvj this is what was told: 
- Use Duply/Duplicity as backup client (free, open source, running on Linux) -> this would run on our AuraCast server. 
- Set up cron task for calling Duply every day, week, etc.
- Config Duply to send new backups to external storage (e.g. Amazon S3, Backblaze B2) .

The price of all this is the storage, which shouldn't be expensive.

**Comment by gammaw** [comment]
Should be clear for now
