### ISSUE TITLE
Change artist and title 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#98]
Now we have to add show title in "song title" and episode title in "song artist". Turn it the other way around

**Comment by gammaw** [comment]
@pvj please do prod migration off-time. If you touch DB, test it on dev first!!!!!

**Comment by pvj** [comment]
We swapped values on dev db then invalidated cache in Redis on the artist-v-song-title-switch branch on dev machine and it seems like the HTML is rendered such that artist goes into top line title subtitle. 

If this is the intended presentation we are good to merge and do the db update. 

If this is unintended I'll push change where HTML is swapped in radio_player too.

**Comment by gammaw** [comment]
Adapt set url logic on player: change title to artist in Vue file
