### ISSUE TITLE
News improvements

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#99]
- Delete "Open news item" -> keep >> only
- Delete READ MORE NEWS link -> make news thumbnail "area" clickable

**Comment by baxgas** [comment]
899b9b082d704cb9807bee6b2c14bde005ab9d44 also fixed here

**Comment by gammaw** [comment]
> Delete "Open news item" -> keep >> only

@baxgas isn't >> missing? 

> Delete READ MORE NEWS link -> make news thumbnail "area" clickable

You didn't do the clickable area right?

**Comment by baxgas** [comment]
It was made with the #89 issue branch, sorry for not making a new one. The News item Title and Thumbnail is clickable, and the Title of the News on the Home page leads to the News category.
